apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend
spec:
  selector:
    app: {{ .Chart.Name }}-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
# Repeat for other services
