apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-prod
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/your-repo'
    path: charts/microservices
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated: {}
